TestEOS/Models/ErrorViewModel.cs
using System;

namespace TestEOS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestEOS/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TestEOS.Models;

namespace TestEOS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestEOS/Controllers/LogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using NLog;
using System;
using System.Threading;
using TestEOS.OutputLogs;

namespace TestEOS.Controllers
{
    public class LogController : Controller
    {
        private static OneTask _hosted;
        public LogController( OneTask hosted)
        {
            _hosted = hosted;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Start() 
        {
            _hosted.StartAsync(CancellationToken.None);
            return new EmptyResult();
        }

        public IActionResult Stop()
        {
            _hosted.StopAsync(CancellationToken.None);
            return new EmptyResult();
        }

    }
}

TestEOS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">


</div>

TestEOS/Views/Log/Index.cshtml
@{
    ViewData["Title"] = "Page";
}

<h1>Log Control</h1>

<form asp-controller="Log" method="post">
    <button type="button" id="start" class="btn btn-sm btn-warning active" data-action="start">Запустить фоновую задачу!</button>
    <button type="button" id="stop" class="btn bth-sm btn-dark" data-action="stop">Остановить фоновую задачу!</button>
</form>


<script>
    $(document).ready(function () {
        // Handle button click events
        $('button[data-action]').click(function () {
            // Disable current active button
            $('button.active').removeClass('active').prop('disabled', false);
            // Enable clicked button and mark it as active
            $(this).addClass('active').prop('disabled', true);
            // Call the corresponding controller action
            var action = $(this).data('action');
            $.post('/Log/' + action);
        });
    });
</script>

TestEOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestEOS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestEOS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>